version: '3.1'

services:
  snippetBox:
    image: golang:bookworm
    command: tail -f /dev/null
    working_dir: /usr/src/snippetbox
    restart: no
    volumes: 
      - .:/usr/src/snippetbox
  db:
    image: mysql:8.0-bookworm
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: oZrCYn8J31VrxftQcPwtGNOe0
    volumes:
      - ./db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

